<script lang="ts">
	import { Button } from '$lib/components/ui/button';
	import * as Dialog from '$lib/components/ui/dialog';

	interface Props {
		open: boolean;
		onOpenChange: (open: boolean) => void;
	}

	let { open, onOpenChange }: Props = $props();
</script>

<Dialog.Root {open} {onOpenChange}>
	<Dialog.Content class="sm:max-w-xl">
		<Dialog.Header>
			<Dialog.Title>Welcome to Deployable Knowledge</Dialog.Title>
			<Dialog.Description>
				This app runs entirely on your machine - documents, embeddings, and chat all stay local. A
				couple of things need to be set up first.
			</Dialog.Description>
		</Dialog.Header>

		<div class="grid gap-4 text-sm">
			<section class="grid gap-1.5">
				<h3 class="font-medium">1. Install Ollama (required)</h3>
				<p class="text-muted-foreground">
					Chat responses are generated by a local model served through <a
						class="text-primary underline underline-offset-2"
						href="https://ollama.com"
						rel="noreferrer"
						target="_blank">Ollama</a
					>. Without it running, the assistant can't respond.
				</p>
				<ol class="list-decimal space-y-1 pl-5 text-muted-foreground">
					<li>
						Download and install Ollama from <a
							class="text-primary underline underline-offset-2"
							href="https://ollama.com"
							rel="noreferrer"
							target="_blank">ollama.com</a
						>.
					</li>
					<li>
						Pull the default model: <code class="rounded border bg-muted px-1.5 py-0.5 text-xs"
							>ollama pull granite4:350m</code
						>
					</li>
					<li>
						Leave Ollama running in the background (it listens on <code
							class="rounded border bg-muted px-1.5 py-0.5 text-xs">localhost:11434</code
						>).
					</li>
				</ol>
				<p class="text-muted-foreground italic">
					You can swap in a different model or provider later from Settings - this is just the one
					the app is configured to use out of the box.
				</p>
			</section>

			<section class="grid gap-1.5">
				<h3 class="font-medium">2. First-time project setup</h3>
				<ol class="list-decimal space-y-1 pl-5 text-muted-foreground">
					<li><code class="rounded border bg-muted px-1.5 py-0.5 text-xs">npm install</code></li>
					<li>
						<code class="rounded border bg-muted px-1.5 py-0.5 text-xs">npm run dev</code> - this also
						pushes the database schema automatically the first time it runs.
					</li>
				</ol>
			</section>

			<section class="grid gap-1.5">
				<h3 class="font-medium">3. Upload documents</h3>
				<p class="text-muted-foreground">
					Open the Document Library window to browse for a file, or copy a file on your computer and
					paste it directly into the window.
				</p>
			</section>
		</div>

		<Dialog.Footer>
			<Button onclick={() => onOpenChange(false)}>Get started</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
